import { Route } from "@/types";

export const routes: Route[] = [
  {
    id: 1,
    from: "Calabar",
    to: "Ibadan",
    price: 19463,
    duration: "6h 34m",
    departureTime: "03:38 PM",
    transportType: "Luxury Bus",
    stops: ["Zuba", "Ikot Ekpene"],
    availableSeats: 4,
    image: "https://placekitten.com/70/590",
  },
  {
    id: 2,
    from: "Ibadan",
    to: "Owerri",
    price: 10379,
    duration: "2h 30m",
    departureTime: "03:44 PM",
    transportType: "Hiace",
    stops: ["Lokoja"],
    availableSeats: 5,
    image: "https://www.lorempixel.com/422/213",
  },
  {
    id: 3,
    from: "Makurdi",
    to: "Kaduna",
    price: 18016,
    duration: "5h 11m",
    departureTime: "07:17 AM",
    transportType: "Mini Bus",
    stops: ["Lokoja", "Coal Camp"],
    availableSeats: 8,
    image: "https://placekitten.com/1003/878",
  },
  {
    id: 4,
    from: "Jos",
    to: "Aba",
    price: 11535,
    duration: "6h 15m",
    departureTime: "10:59 PM",
    transportType: "Bus",
    stops: ["9th Mile", "Elele", "Ikot Ekpene"],
    availableSeats: 13,
    image: "https://dummyimage.com/326x837",
  },
  {
    id: 5,
    from: "Katsina",
    to: "Maiduguri",
    price: 8094,
    duration: "2h 20m",
    departureTime: "10:39 PM",
    transportType: "SUV",
    stops: ["Elele", "Obollo-Afor", "Ikot Ekpene", "Rijana"],
    availableSeats: 4,
    image: "https://www.lorempixel.com/88/725",
  },
];
