import { BusRoute, Route } from "@/types";

export const sampleRoutes: Route[] = [
  {
    routeId: "1",
    origin: "Abakpa",
    destination: "Gariki",
    price: 1200,
    duration: "1h 30m",
    image:
      "https://www.shutterstock.com/image-photo/aerial-view-bustling-urban-landscape-600nw-2550888697.jpg",
    description: "Direct flight from Lagos to Abuja",
    distance: "534 km",
  },
  {
    routeId: "2",
    origin: "Enugu",
    destination: "Nsukka",
    price: 3500,
    duration: "1h 30m",
    image:
      "https://www.nairaland.com/attachments/5928171_2127234810287541038941947456967265889492231n_jpega075271d01fed7cb95498c07e6fe6075",
    description: "Direct flight from Lagos to Port Harcourt",
    distance: "617 km",
  },
  {
    routeId: "3",
    origin: "Abuja",
    destination: "Kaduna",
    price: 18000,
    duration: "13h",
    image:
      "https://as2.ftcdn.net/jpg/05/11/87/61/1000_F_511876132_lvR1nkSpnniH26xvN5bX84CZCPDScVFI.jpg",
    description: "Direct flight from Abuja to Kano",
    distance: "376 km",
  },
  {
    routeId: "4",
    origin: "Port Harcourt",
    destination: "Owerri",
    price: 6000,
    duration: "3h 45m",
    image:
      "https://www.shutterstock.com/shutterstock/videos/3458108987/thumb/1.jpg?ip=x480",
    description: "Direct flight from Kano to Lagos",
    distance: "754 km",
  },
  {
    routeId: "5",
    origin: "Port Harcourt",
    destination: "Abuja",
    price: 20000,
    duration: "1h 10m",
    image: "/placeholder.svg",
    description: "Direct flight from Port Harcourt to Abuja",
    distance: "498 km",
  },
  {
    routeId: "6",
    origin: "Enugu",
    destination: "Lagos",
    price: 23000,
    duration: "1h 20m",
    image: "/placeholder.svg",
    description: "Direct flight from Enugu to Lagos",
    distance: "527 km",
  },
  {
    routeId: "7",
    origin: "Abuja",
    destination: "Enugu",
    price: 19000,
    duration: "1h 05m",
    image: "/placeholder.svg",
    description: "Direct flight from Abuja to Enugu",
    distance: "412 km",
  },
  {
    routeId: "8",
    origin: "Lagos",
    destination: "Kano",
    price: 28000,
    duration: "1h 50m",
    image: "/placeholder.svg",
    description: "Direct flight from Lagos to Kano",
    distance: "754 km",
  },
];

// Promotions data
export const promotions = [
  {
    id: 1,
    title: "Weekend Special",
    description: "20% off on all weekend journeys",
    code: "WEEKEND20",
    validUntil: "June 30, 2025",
  },
  {
    id: 2,
    title: "Family Package",
    description: "Book for 4 or more and get 15% discount",
    code: "FAMILY15",
    validUntil: "July 15, 2025",
  },
  {
    id: 3,
    title: "Early Bird",
    description: "Book 7 days in advance and save 10%",
    code: "EARLY10",
    validUntil: "Ongoing",
  },
];

export const allBusRoutes: BusRoute[] = [
  {
    id: "1",
    company: "HorizonJet",
    logo: "HJ",
    departureTime: "22:25",
    arrivalTime: "07:06",
    duration: "8h 41m",
    stops: 1,
    price: 27550,
    available_seats: 23,
    originCity: "Abakpa",
    destinationCity: "Gariki",
  },
  {
    id: "2",
    company: "Altitude Express",
    logo: "AE",
    departureTime: "06:30",
    arrivalTime: "07:55",
    duration: "1h 25m",
    stops: 0, // Direct
    price: 20600,
    available_seats: 15,
    originCity: "Enugu",
    destinationCity: "Nsukka",
  },
  {
    id: "3",
    company: "Cloudy Transit",
    logo: "CT",
    departureTime: "13:19",
    arrivalTime: "14:45",
    duration: "1h 26m",
    stops: 0, // Direct
    price: 14850,
    available_seats: 32,
    originCity: "Abuja",
    destinationCity: "Kaduna",
  },
  {
    id: "4",
    company: "Cloudy Transit",
    logo: "CT",
    departureTime: "18:13",
    arrivalTime: "03:40", // Next day arrival
    duration: "9h 27m",
    stops: 1,
    price: 38015,
    available_seats: 8,
    originCity: "Port Harcourt",
    destinationCity: "Owerri",
  },
  {
    id: "5",
    company: "Altitude Express",
    logo: "AE",
    departureTime: "06:20",
    arrivalTime: "15:46",
    duration: "9h 26m",
    stops: 2,
    price: 26910,
    available_seats: 19,
    originCity: "Lagos",
    destinationCity: "Abuja",
  },
  {
    id: "6",
    company: "HorizonJet",
    logo: "HJ",
    departureTime: "19:15",
    arrivalTime: "04:45", // Next day
    duration: "9h 30m",
    stops: 0, // Direct
    price: 54910,
    available_seats: 27,
    originCity: "Lagos",
    destinationCity: "Abuja",
  },
  {
    id: "7",
    company: "HorizonJet",
    logo: "HJ",
    departureTime: "06:01",
    arrivalTime: "07:28",
    duration: "1h 27m",
    stops: 0, // Direct
    price: 20050,
    available_seats: 11,
    originCity: "Lagos",
    destinationCity: "Ibadan",
  },
  {
    id: "8",
    company: "FlyScape",
    logo: "FS",
    departureTime: "08:40",
    arrivalTime: "18:00",
    duration: "9h 20m",
    stops: 1,
    price: 54910,
    available_seats: 5,
    originCity: "Lagos",
    destinationCity: "Abuja",
  },
  {
    id: "9",
    company: "Capital Connect",
    logo: "CC",
    departureTime: "09:00",
    arrivalTime: "18:30",
    duration: "9h 30m",
    stops: 0,
    price: 42000,
    available_seats: 30,
    originCity: "Abuja",
    destinationCity: "Lagos",
  },
  {
    id: "10",
    company: "Capital Connect",
    logo: "CC",
    departureTime: "21:00",
    arrivalTime: "06:30", // Next day
    duration: "9h 30m",
    stops: 1,
    price: 39500,
    available_seats: 12,
    originCity: "Abuja",
    destinationCity: "Lagos",
  },
  {
    // Example for a route that might not be commonly searched
    id: "11",
    company: "Northern Star",
    logo: "NS",
    departureTime: "07:00",
    arrivalTime: "15:00",
    duration: "8h 00m",
    stops: 1,
    price: 35000,
    available_seats: 25,
    originCity: "Abuja",
    destinationCity: "Kano",
  },
];
